version: '3.9'

services: 
  postgres:
    image: postgres:16
    container_name: meu_postgres
    environment:
      POSTGRESS_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata: