version: '3.9'

services: 
  postgres:
    image: postgres:16
    container_name: meu_postgres
    environment:
      POSTGRESS_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build: ./api
    container_name: games_api
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: npm run start:dev  

volumes:
  pgdata: