version: "3.9"

services:
  backend:
    image: games-api
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./my-react-app
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
